### PR TITLE
Null safety migration

### LINKED ISSUE #15: Migrating to null safety
I was wondering if there is already a roadmap for migrating this library to null safety?
https://dart.dev/null-safety/migration-guide

### PR DESCRIPTION
**Pull request by Jjagg**
Fixes #15 :)

### CODE REVIEW

**Comment by drogel** [comment]
Hi @Jjagg, huge thanks for proposing the migration. I have been quite busy at work and I did not have much time to read all the new stuff that comes with the recent release of Flutter 2, but I want to update my packages and personal projects to null safety now that Flutter 2 is out in the stable channel.

So expect to have this MR reviewed pretty soon. Thanks again for your work on this.

**Comment by Jjagg** [comment]
No worries :)

**Comment by drogel** [comment]
Hi @Jjagg, you've done just what I would have done if I had done the migration myself, so huge thanks for this. I'm going to review the documentation, README etc. and update it for the null safety version, and publish the null safe version of the package after that.

Thanks for contributing!

**Comment by Jjagg** [comment]
Awesome! You're very welcome 😉
Thanks for the great package!

**Pull request merged**
